### ISSUE TITLE
Problematic Guzzle 7 lock-in

### ISSUE THREAD

**Issue by ivastly** [DoclerLabs/api-client-generator#14]
Current version of the generated client is locked to `guzzle ^7.1`. PHP version accepts PHP 7.1 as well:
<img width="480" alt="image" src="https://user-images.githubusercontent.com/919655/96416055-c41ca680-11ef-11eb-8ae3-b6379598f1dd.png">

However, guzzle version 7 is not compatible with PHP 7.1, the minimum PHP version is 7.2, as [stated in the guzzle docs](https://github.com/guzzle/guzzle/blob/master/UPGRADING.md).

Moreover, locking in to guzzle 7  makes it impossible to use the client in projects having some other guzzle versions installed already. I have stumbled upon this problem few times already. So, can we widen guzzle support to at least`^6 || ^7` ❓ Otherwise we cut huge piece of the market by locking to just guzzle 7.

**Comment by mikemadisonweb** [comment]
Thanks @ivastly for raising an issue.
Actually, it is not locked in, but the opposite. The implementation depends only on PSR-18 interface and there is a choice of base HTTP clients already that you can choose. It was missing in the configuration documentation though. Now it is up-to-date: https://github.com/DoclerLabs/api-client-generator#configuration I have a dream of nice, descriptive documentation for this package, but it is not the case yet, sorry for that.
So it is up to you, if you want guzzle version 6, you need to pass HTTP_CLIENT=guzzle6. That would also go to the composer.json template.

**Comment by ivastly** [comment]
So nice, thank you!
