### ISSUE TITLE
Adding generator on https://openapi.tools

### ISSUE THREAD

**Issue by vsouz4** [DoclerLabs/api-client-generator#23]
What do you guys think about creating PR on https://openapi.tools/, so this project "becomes more visible"? Do we need to do anything before that (e.g. improve documentation, missing features etc.)?

**Comment by ivastly** [comment]
Let's do it! If they don't accept the project right away, let's apply the changes they want and knock again.

**Comment by mikemadisonweb** [comment]
Great idea, I guess this generator not much worse compared to the ones which are already there. The weakest part of our generator is documentation in my opinion. Feature-wise it is decent.

**Comment by JasonBenett** [comment]
As @mikemadisonweb said, let's document a bit more the project and after that creating the PR.

**Comment by mikemadisonweb** [comment]
Another thing, in my opinion, is that we tried the generator mostly on Docler internal specifications, which are usually refined and well-written. We need to try it out more on publicly available ones. I'll do that when I would have some time.

**Comment by vsouz4** [comment]
https://github.com/apisyouwonthate/openapi.tools/pull/233 🤞 😄
