### ISSUE TITLE
API test stubs as part of generated client?

### ISSUE THREAD

**Issue by ivastly** [DoclerLabs/api-client-generator#3]
# Problem
Every time I integrate with SomeAPI, I use auto-generated client of SomeAPI. 
However, For my own API/System tests I want to have Some API's endpoints mocked. This mocks are boring and mostly the same in every client - "boilerplate" code.

# Question
Can we have some kind of generated mock stubs shipped together with the client? So, as autogenerated API client user, I write my system tests using mocking functionality provided by auto-generated Codeception module, bundled with the auto-generated client. 

Not sure if it is good idea to couple with Codeception here, and also how to do it without coupling to some specific mocking server (?) Just want to hear your ideas on it.

**Comment by mikemadisonweb** [comment]
Hi Vasiliy! Well, I share your concerns about coupling with a specific tool, also actually mock servers as a tool has a different purpose. It is not something that is used alongside the client all of the time. In my opinion, we need to concentrate on client generation specifically. It follows the great postulate of (Unix philosophy)[https://en.wikipedia.org/wiki/Unix_philosophy]: "do one thing and do it well".

There are a variety of tools out there you can use to generate and fire up mock servers from the OpenAPI specification, e.g. [prism](https://github.com/stoplightio/prism).
