### ISSUE TITLE
Add anyOf type support

### ISSUE THREAD

**Issue by vabalazs82** [DoclerLabs/api-client-generator#34]
Dear all,

The very old version of this generator is supported the anyOf multi types, but the new ones is not, it would be nice to put the support back.
https://swagger.io/docs/specification/data-models/oneof-anyof-allof-not/

WDYT?

**Comment by vsouz4** [comment]
please check if this version is already working for you
```
## [5.3.0] - 2021-04-13
### Added
 - Support for `mixed` parameter type
 - Support for anyOf `mixed` parameter type
```
