### ISSUE TITLE
Add the version of the api generator to generated api-client readme

### ISSUE THREAD

**Issue by vabalazs82** [DoclerLabs/api-client-generator#35]
Dear all,

It would be very useful if the api client generator version (which is generated the api client) is added to the generated api-client source code.

In this case if need to update generated api client, we will know which version have to use to regenerate.

WDYT?

**Comment by JasonBenett** [comment]
I agree.

You mean in the generated README.md file, right?

**Comment by vsouz4** [comment]
I agree as well. Right now we're manually maintaining this README generator version LOL

**Comment by vabalazs82** [comment]
> I agree.
> 
> You mean in the generated README.md file, right?

Yes

**Comment by vsouz4** [comment]
it's done, check the diff after regenerating a client with generator version 5.6.0:
```
diff --git a/README.md b/README.md
index fe7f355..5f3a044 100644
--- a/README.md
+++ b/README.md
@@ -11,8 +11,8 @@ docker run -it \
 -e OPENAPI=/openapi.yaml \
 -e OUTPUT_DIR=/client \
 -e PACKAGE=dh-jasmin/story-api-client \
 -e CLIENT_PHP_VERSION=7.2 \
-dhlabs/api-client-generator:4.1
+dhlabs/api-client-generator:5.6.0
```
the generator image has the generator version as an environment variable:
```
$ docker run --rm -it dhlabs/api-client-generator:5.6.0 sh
/generator/bin # env|grep -i generator_version
API_CLIENT_GENERATOR_VERSION=5.6.0
```
