### ISSUE TITLE
Why psr/http-client-implementation required by generated libraries?

### ISSUE THREAD

**Issue by szhajdu** [DoclerLabs/api-client-generator#55]
Hi,

the generated libraries require psr/http-client-implementation virtual package. Can you explain the reason behind this? If I understand the usage of virtual packages, now I cannot use my own http-client implementation in my app, but only if I provide a library for that or use 3rd party.

Interesting post about it: https://matthiasnoback.nl/2014/10/composer-provide-and-dependency-inversion/

**Comment by vsouz4** [comment]
a bit of context https://github.com/DoclerLabs/api-client-generator/pull/21#discussion_r532450379

btw I'm not fond of this either, I'd rather "suggest" rather than force (like I said in the above thread) but I'm open for ideas @mikemadisonweb @JasonBenett @pelyib @ivastly wdyt?

**Comment by JasonBenett** [comment]
> If I understand the usage of virtual packages, now I cannot use my own http-client implementation in my app, but only if I provide a library for that or use 3rd party.

Indeed!

From my side, I like this solution so nothing to add to be honest.

**Comment by szhajdu** [comment]
But in reality, virtual package does not check anything. The real dependency is psr/http-client and their interfaces. If any implementation fulfills this requirement, the generated client would work. So still not understand why we need this extra restriction. It adds nothing, but unnecessary dependency.

**Comment by JasonBenett** [comment]
> virtual package does not check anything

Well it's not totally true. It prevents from installing the generated client in an application which does not have any PSR18 implementation installed, which is a prerequisite. But where you are totally right is when saying that it reduces the possibility of usages if, for instance, you are using your own custom implementation without using composer or even a composer package which is not using the "provide" option.

So yes, you changed my mind and it would probably makes sense to remove this restriction indeed!

**Comment by vsouz4** [comment]
cool, seems we have an agreement then 😄 I'll have some time next week to remove this and add couple of psr18 implementation ["suggest"ions](https://getcomposer.org/doc/04-schema.md#suggest)... if nobody's done anything about it still...
