### ISSUE TITLE
Support duplicate parameter names

### ISSUE THREAD

**Issue by zukk** [DoclerLabs/api-client-generator#59]
Generated schema files for parameters with same names overwrite existing ones.

**Comment by vsouz4** [comment]
@zukk do you have an example?

**Comment by zukk** [comment]
Attached a zip with generated example:
[test.zip](https://github.com/DoclerLabs/api-client-generator/files/7461394/test.zip)

See spec inside: doc/duplicateDeepObjectNameBug.yaml
Generate string:
`OPENAPI=/home/zukk/Downloads/duplicateDeepObjectNameBug.yaml NAMESPACE=test OUTPUT_DIR=test PACKAGE=test bin/api-client-generator generate`

Inside, in a dir named src/Schema you'll see only one class Filter.php for a second path in spec, overwrote previously created Filter.php for a first path.

So, using a first path with a proper Filter is impossible..

**Comment by vsouz4** [comment]
indeed we missed passing the $ref name on request parameters, linked a PR with the fix, and running generator on your example now results in:
```
$ find src/Schema
src/Schema
src/Schema/Mapper
src/Schema/Mapper/SchemaMapperInterface.php
src/Schema/FirstFilter.php
src/Schema/SerializableInterface.php
src/Schema/SecondFilter.php
```
