### ISSUE TITLE
Removing /src directory content during generation

### ISSUE THREAD

**Issue by JasonBenett** [DoclerLabs/api-client-generator#63]
Hello!

To avoid having dead code in the generated clients (happening when removing some parts from the openapi spec), I would suggest to apply something like:

- rename /src to /src_old.
- generate the new files in /src.
- if something goes wrong, revert. If everything is fine, remove the /src_old dir.

Currently, I remove manually `/src` folder before generating the client to address this behaviour. 
If we do not want to enforce this (I don't see why so far), maybe it can be handled with an option passed to the command like `CLEAN=1` for example.

What do you think?

**Comment by vsouz4** [comment]
let's do it!

btw I also don't see any reason to not do it by default, we could release major version and later (if really needed) add an option to disable this cleanup behaviour (instead of an option to enable it).
